"""Model manifest types for bundle discovery and metadata.

These types enable model discovery and registration in bundles,
providing metadata about available models, their scenarios, and parameters.
The manifest serves as a registry for what's available in a bundle.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class ModelEntry:
    """Registry entry for a discovered model in a bundle.

    Describes a single model's capabilities and metadata for discovery.
    Each model can have multiple scenarios that represent different
    configurations or use cases.

    Attributes:
        entrypoint_base: Python import path to model class (e.g., 'models.seir.StochasticSEIR')
        scenarios: List of available scenarios for this model
        outputs: List of output extractors this model provides
        parameters: List of parameter names this model accepts
        model_digest: BLAKE2b-256 hash of model implementation (64-char hex)
    """
    entrypoint_base: str
    scenarios: List[str]
    outputs: List[str]
    parameters: List[str]
    model_digest: str

    def __post_init__(self):
        # Validate model_digest format (64-char hex)
        if not self.model_digest:
            raise ValueError("model_digest must be non-empty")
        if not (len(self.model_digest) == 64 and
                all(c in "0123456789abcdef" for c in self.model_digest)):
            raise ValueError("model_digest must be 64-character hex string")

        # Validate lists are non-empty
        if not self.scenarios:
            raise ValueError("scenarios must contain at least one scenario")
        if not self.parameters:
            raise ValueError("parameters must contain at least one parameter")

    def get_entrypoints(self) -> List[str]:
        """Get full entrypoint IDs for all scenarios.

        Returns:
            List of entrypoint IDs like 'models.seir.StochasticSEIR/baseline'
        """
        return [f"{self.entrypoint_base}/{scenario}" for scenario in self.scenarios]


@dataclass(frozen=True)
class BundleManifest:
    """Manifest describing all models in a bundle.

    Provides a registry of available models for discovery and task generation.
    This is generated by the science package (e.g., modelops-calabaria) and
    consumed by infrastructure (e.g., modelops) to understand what can be executed.

    Attributes:
        bundle_ref: OCI reference or path to bundle
        bundle_digest: BLAKE2b-256 hash of entire bundle (64-char hex)
        models: Map of model identifiers to their metadata
        version: Manifest format version for compatibility
    """
    bundle_ref: str
    bundle_digest: str
    models: Dict[str, ModelEntry]
    version: int = 1

    def __post_init__(self):
        # Validate bundle_digest format
        if not self.bundle_digest:
            raise ValueError("bundle_digest must be non-empty")
        if not (len(self.bundle_digest) == 64 and
                all(c in "0123456789abcdef" for c in self.bundle_digest)):
            raise ValueError("bundle_digest must be 64-character hex string")

        # Validate bundle_ref
        if not self.bundle_ref:
            raise ValueError("bundle_ref must be non-empty")

        # Validate models
        if not self.models:
            raise ValueError("models must contain at least one model")

    def get_model_by_entrypoint(self, entrypoint_base: str) -> ModelEntry | None:
        """Look up a model by its entrypoint base.

        Args:
            entrypoint_base: Python import path like 'models.seir.StochasticSEIR'

        Returns:
            ModelEntry if found, None otherwise
        """
        return self.models.get(entrypoint_base)

    def list_all_entrypoints(self) -> List[str]:
        """Get all available entrypoint IDs across all models.

        Returns:
            List of all entrypoint IDs with scenarios
        """
        entrypoints = []
        for model in self.models.values():
            entrypoints.extend(model.get_entrypoints())
        return sorted(entrypoints)


__all__ = ["ModelEntry", "BundleManifest"]